src/improveo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('', include('reports.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from . import views


app_name = "posts"
urlpatterns = [
    path('', views.PostCreateView.as_view(), name='post_list'),
    path('<int:pk>/detail/', views.GeneralDetailPost.as_view(), name='gp-detail'),
    path('<int:pk1>/<int:pk>/detail/',
         views.ProblemDetailView.as_view(), name='pp-detail'),
    path('like/', views.like_post, name='post_like'),

]

src/reports/urls.py
from django.urls import path
from . import views


app_name = "reports"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('reports/', views.SelectView.as_view(), name="select_report"),
    path('reports/summary', views.main_report_summary, name="report_summary"),
    path('reports/<str:production_line>/',
         views.report_view, name='report_view'),
    path('reports/delete/<int:pk>/', views.delete_report, name='delete_report'),
    path('reports/<str:production_line>/<int:pk>/update',
         views.UpdateReportView.as_view(), name="update_report"),
    path('reports/generate/pdf/', views.get_generated_problems_in_pdf, name="pdf"),
]

src/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <script src="https://use.fontawesome.com/016034d552.js"></script>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">

        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

        <title>Improveo| {% block title %}{% endblock title %}</title>
    </head>
    
    <body>
        {% include 'navbar.html' %}

        <section class="bg-dark p-3">
            <div class="pt-big">
                {% block content %}{% endblock content %}
            </div>
        </section>

        {% include 'footer.html' %}











        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        {% block script %}{% endblock script %}
    </body>
</html>

src/templates/footer.html
<footer>
    <div class="col-12">
        <div class="row">
            <div class="col-8 p-5">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu eleifend turpis, sed sagittis felis. Morbi viverra dapibus pharetra. Nam placerat rhoncus ante, non consequat leo consectetur at. In hac habitasse platea dictumst. Donec tristique sollicitudin faucibus. Phasellus vitae libero sit amet sapien vestibulum scelerisque. Nullam porttitor tempor mattis. Pellentesque dignissim malesuada euismod. Nunc erat ex, fermentum at rhoncus ac, iaculis id eros. Sed gravida ante odio. Morbi bibendum interdum mattis. Nam blandit gravida nisi a ullamcorper. Vestibulum non eleifend nisl, et semper tortor. Donec ac turpis viverra, gravida risus ac, hendrerit magna. Aliquam erat volutpat.

                In imperdiet tristique nisl vel dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis pretium lectus in ultrices posuere. Morbi quis euismod magna. Nullam accumsan ac neque eu cursus. Praesent ipsum mauris, scelerisque a sem nec, posuere ornare ante. Nullam congue interdum bibendum. In vulputate ut erat a egestas. Sed pretium velit lectus, quis tempus dui varius sit amet. Curabitur at auctor arcu, molestie elementum nisi. Maecenas sem enim, accumsan ut magna lobortis, lobortis ullamcorper lectus.
            </div>

            <div class="col-4 p-5">
                <div class="container h1 text-right">
                    <i class="fab fa-facebook-f ml-2"></i>
                    <i class="fab fa-instagram ml-2"></i>
                    <i class="fab fa-twitter ml-2"></i>
                    <i class="fab fa-youtube ml-2"></i>

                </div>
                <div>
                    some image
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 bg-white text-center p-2"><p>&copy; 2019 Improveo<p></div>
</footer>

src/templates/navbar.html
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark border-bottom border-secondary fixed-top py-3">
    <div class="container">
        <a class="navbar-brand" href="{{ path_home }}">Improveo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:post_list' %}">Board</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:select_report' %}">Get report</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:pdf' %}">Todays PDF</a>
                </li>        
            </ul>

            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="" class="nav-link">
                            <img src="{{ picture.url }}" alt="profile picture" class="img-avatar">
                            <span class="ml-2">{{ request.user }}</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>