src/improveo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('', include('reports.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from . import views


app_name = "posts"
urlpatterns = [
    path('', views.PostCreateView.as_view(), name='post_list'),
    path('<int:pk>/detail/', views.GeneralDetailPost.as_view(), name='gp-detail'),
    path('<int:pk1>/<int:pk>/detail/',
         views.ProblemDetailView.as_view(), name='pp-detail'),
    path('like/', views.like_post, name='post_like'),

]

src/posts/models.py
import os
import uuid

from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse

from profiles.models import Profile
from reports.models import Report, ProblemReported


LIKES_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class PostManager(models.Manager):
    def get_public(self):
        return self.filter(problem_reported__public=True)


class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    liked = models.ManyToManyField(Profile, related_name='liked', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def num_likes(self):
        return self.liked.all().count()

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'


class ProblemPost(Post):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    problem_reported = models.ForeignKey(
        ProblemReported, on_delete=models.CASCADE)
    objects = PostManager()

    def __str__(self):
        return f"{self.problem_reported.description[:50]}"

    def get_absolute_url(self):
        return reverse("posts:pp-detail", kwargs={'pk1': self.pk, 'pk': self.problem_reported.id})

    class Meta:
        verbose_name = 'Problem Post'
        verbose_name_plural = 'Problem Posts'


def get_upload_path(instance, filename):
    extension = filename.split('.')[-1]
    filename = f"{uuid.uuid4}.{extension}"
    return os.path.join('uploads/posts/images', filename)


class GeneralPost(Post):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=360)
    img = models.ImageField(upload_to=get_upload_path, blank=True, validators=[
                            FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:gp-detail", kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'General Post'
        verbose_name_plural = 'General Posts'


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(
        max_length=10, choices=LIKES_CHOICES, default="Like")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.post} was {self.value}d"


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(GeneralPost, on_delete=models.CASCADE)
    body = models.TextField(max_length=360)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.pk}'

    class Meta:
        ordering = ('-created',)

src/posts/forms.py
from django import forms
from django.core.validators import ValidationError

from .models import GeneralPost, Comment


class PostForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = GeneralPost
        fields = ('title', 'description', 'img', )

    def clean_description(self):
        desc = self.cleaned_data.get('description')
        if len(desc) < 10:
            raise ValidationError('Description too short')
        return desc


class CommentForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.Textarea(
        attrs={'rows': 3, 'placeholder': 'Your comment here...'}))

    class Meta:
        model = Comment
        fields = ('body',)

src/posts/views.py
from itertools import chain

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from .forms import PostForm
from .models import ProblemPost, GeneralPost, Post, Like
from .mixins import FormUserRequiredMixin
from profiles.models import Profile


class ProblemDetailView(LoginRequiredMixin, DetailView):
    model = ProblemPost
    template_name = 'posts/detail.html'
    pk_url_kwarg = 'pk1'
    context_object_name = 'post'


class GeneralDetailPost(LoginRequiredMixin, DetailView):
    model = GeneralPost
    template_name = 'posts/detail.html'


class PostCreateView(FormUserRequiredMixin, CreateView):
    form_class = PostForm
    template_name = 'posts/board.html'
    success_url = reverse_lazy('posts:post_list')

    def get_context_data(self, **kwargs):
        qs1 = ProblemPost.objects.get_public()
        qs2 = GeneralPost.objects.all()
        qs = sorted(chain(qs1, qs2), reverse=True, key=lambda obj: obj.created)
        context = super().get_context_data(**kwargs)
        context["object_list"] = qs
        return context


def like_post(request):
    user = request.user
    profile = Profile.objects.get(user=user)

    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post = Post.objects.get(id=post_id)

        if profile in post.liked.all():
            post.liked.remove(profile)
        else:
            post.liked.add(profile)

    like, created = Like.objects.get_or_create(user=profile, post_id=post_id)
    if not created:
        if Like.value == "Like":
            Like.value = "Unlike"
        else:
            Like.value = "Like"
    like.save()
    return redirect('posts:post_list')

src/posts/templates/posts/board.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Board{% endblock title %}

{% block content %}
    <div class="container bg-light p-3 pb-4 rounded">
        <div class="col-11 mx-auto border rounded  bg-white rounded p-3">
            <form action="" method="post" class="form-group" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
        <br>
        {% for post in object_list %}
            {% if post.problem_reported %}
                <div class="col-11 mx-auto card card-body mt-3 border border-danger">
                    <small class="text-muted">
                        author: {{ post.problem_reported.user }} | {{ post.problem_reported.created|timesince }} ago.
                    </small>
                    <hr>
                    <h5 class="card-title">{{ post.problem_reported.category }}</h5>
                    <p class="card-text">{{ post.problem_reported.description }}</p>
            {% else %}
                <div class="col-11  mx-auto card card-body mt-3 border border-primary">
                    {% if post.img %}
                        <div class="mb-3">
                            <img src="{{ post.img.url }}" alt="post image" class="w-25 h-25 border border-dark rounded float-right">
                        </div>
                    {% endif %}
                    <small class="text-muted">
                        author: {{ post.author }} | {{ post.created|timesince }} ago.
                    </small>
                    <hr>
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.description }}</p>
            {% endif %}
                    <div class="row mt-3">
                        <div class="col-4">
                            <form action="{% url 'posts:post_like' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{ post.id }}">
                                
                                {% if profile not in post.liked.all %}
                                    <button type="submit" class="btn btn-link">
                                        <i class="far fa-thumbs-up"></i>
                                        <span class="ml-2">Like</span>
                                    </button>
                                {% else %}
                                    <button type="submit" class="btn btn-link">
                                        <i class="far fa-thumbs-down"></i>
                                        <span class="ml-2">Unlike</span>
                                    </button>
                                {% endif %}    
                                <span>{{ post.liked.all.count }} like{{ post.liked.all.count|pluralize }}</span>
                            </form>
                        </div>
                        <div class="col-4">
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">
                                <span class="">
                                    Details <i class="fas fa-search ml-1"></i>
                                </span>
                            </a>
                        </div>
                    </div>
                </div> <!-- end card -->
        {% endfor %}
    </div>
{% endblock content %}

src/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block title %}Post Detail{% endblock title %}

{% block content %}
    {% if post.report %}
        <h1>Report</h1>
    {% else %}
        <h1>No Reports Here</h1>
    {% endif %}
{% endblock content %}