src/improveo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('', include('reports.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from . import views


app_name = "posts"
urlpatterns = [
    path('', views.PostCreateView.as_view(), name='post_list'),
    path('<int:pk>/detail/', views.GeneralDetailPost.as_view(), name='gp-detail'),
    path('<int:pk1>/<int:pk>/detail/',
         views.ProblemDetailView.as_view(), name='pp-detail'),
    path('like/', views.like_post, name='post_like'),

]

src/reports/urls.py
from django.urls import path
from . import views


app_name = "reports"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('reports/', views.SelectView.as_view(), name="select_report"),
    path('reports/summary', views.main_report_summary, name="report_summary"),
    path('reports/<str:production_line>/',
         views.report_view, name='report_view'),
    path('reports/delete/<int:pk>/', views.delete_report, name='delete_report'),
    path('reports/<str:production_line>/<int:pk>/update',
         views.UpdateReportView.as_view(), name="update_report"),
    path('reports/generate/pdf/', views.get_generated_problems_in_pdf, name="pdf"),
]

src/reports/models.py
from datetime import datetime
import random
import string


from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

from areas.models import ProductionLine
from categories.models import Category
from products.models import Product


# custom variables to be used in models
HOURS = ((str(i), str(i)) for i in range(1, 25))
HOURS2 = ((str(i), str(i)) for i in range(1, 25))
el = [i for i in string.ascii_uppercase] + [i for i in range(10)]


# define a custom  report queryset to add some methods to use them in the custom manager
class ReportQuerySet(models.QuerySet):
    def filter_by_line_and_day(self, day, line_id):
        return self.filter(day=day, production_line__id=line_id)

    def aggregate_execution(self):
        return self.aggregate(Sum('execution'))

    def aggregate_plan(self):
        return self.aggregate(Sum('plan'))


# define custom  report manager
class ReportManager(models.Manager):
    # using the custome queryset inside the custom manager
    def get_queryset(self):
        return ReportQuerySet(self.model, using=self._db)

    def filter_by_line_and_day(self, day, line_id):
        return self.get_queryset().filter_by_line_and_day(day, line_id)

    def aggregate_execution(self):
        return self.get_queryset().aggregate_execution()

    def aggregate_plan(self):
        return self.get_queryset().aggregate_plan()


class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    production_line = models.ForeignKey(
        ProductionLine, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    day = models.DateField(default=timezone.now)
    start_hour = models.CharField(max_length=2, choices=HOURS)
    end_hour = models.CharField(max_length=2, choices=HOURS2)
    # The amount you want to produce
    plan = models.PositiveIntegerField()
    # The actual produced quantity
    execution = models.PositiveIntegerField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    # instantiate the ReportManager
    objects = ReportManager()

    # define a function for customly formatting date
    def get_day(self):
        return self.day.strftime('%d/%m/%Y')

    def get_absolute_url(self):
        return reverse("reports:update_report", kwargs={"production_line": self.production_line, "pk": self.pk})

    def __str__(self):
        return f"{self.start_hour}-{self.end_hour}-{self.production_line}"

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Report'
        verbose_name_plural = 'Reports'


def random_code():
    random.shuffle(el)
    code = [str(x) for x in el[:12]]
    str_code = ''.join(code)
    return str_code


# define custom  report manager
class ProblemReportedManager(models.Manager):
    def get_problem_by_day_and_line(self, day, line):
        return super().get_queryset().filter(report__day=day, report__production_line__name=line)

    # get problems of the current day
    def problems_from_today(self):
        now = datetime.now().strftime('%Y-%m-%d')
        return super().get_queryset().filter(report__day=now)


class ProblemReported(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    description = models.TextField()
    problem_id = models.CharField(
        max_length=12, unique=True, blank=True, default=random_code)
    # how much time does it take to solve the problem
    breakdown = models.PositiveIntegerField()
    public = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    # custom manager
    objects = ProblemReportedManager()

    def __str__(self):
        return f"{self.category.name}-{self.description[:20]}"

    class Meta:
        verbose_name = 'problem reported'
        verbose_name_plural = 'problems reported'

src/reports/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from .models import Report, ProblemReported
from areas.models import ProductionLine


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        # fields = "__all__"
        exclude = ('user', 'production_line',)

    def __init__(self, *args, **kwargs):
        production_line = kwargs.pop('production_line', None)
        super(ReportForm, self).__init__(*args, **kwargs)
        if production_line is not None:
            line = get_object_or_404(ProductionLine, name=production_line)
            self.fields['product'].queryset = line.products.all()


class ProblemReportedForm(forms.ModelForm):
    class Meta:
        model = ProblemReported
        # fields = "__all__"
        exclude = ('user', 'report', 'problem_id',)


class SelectReportForm(forms.Form):
    production_line = forms.ModelChoiceField(
        queryset=ProductionLine.objects.none(), label='')

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SelectReportForm, self).__init__(*args, **kwargs)
        self.fields['production_line'].queryset = ProductionLine.objects.filter(
            team_leader__user__username=self.user)


class ReportResultForm(forms.Form):
    production_line = forms.ModelChoiceField(
        queryset=ProductionLine.objects.all(), label='')
    day = forms.CharField(widget=forms.DateTimeInput(
        attrs={'class': 'datepicker'}
    ))

src/reports/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, FormView
from django.template.loader import render_to_string

from .forms import ReportForm, ProblemReported, ProblemReportedForm, SelectReportForm, ReportResultForm
from .models import Report
from areas.models import ProductionLine

from weasyprint import HTML
import tempfile


@login_required
def get_generated_problems_in_pdf(request):
    problems = ProblemReported.objects.problems_from_today()
    context = {
        'problems': problems,
    }

    # render
    html_string = render_to_string('reports/problems.html', context)
    html = HTML(string=html_string)
    result = html.write_pdf()

    # http response
    response = HttpResponse(content_type='application/pdf;')
    response['content-Disposition'] = 'inline; filename=problem_list.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return response


class HomeView(FormView):
    template_name = 'reports/home.html'
    form_class = SelectReportForm

    # get the current logged in user
    def get_form_kwargs(self):
        kwargs = super(HomeView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def post(self, *args, **kwargs):
        prod_line = self.request.POST.get('prod_line')
        return redirect('reports:report_view', production_line=prod_line)


class SelectView(LoginRequiredMixin, FormView):
    template_name = 'reports/select.html'
    form_class = ReportResultForm
    success_url = reverse_lazy('reports:report_summary')

    def form_valid(self, form):
        # get the selected date from the datepicker
        self.request.session['day'] = self.request.POST.get('day' or None)
        # get the id of the production line selected from the form
        self.request.session['production_line'] = self.request.POST.get(
            'production_line' or None)
        return super(SelectView, self).form_valid(form)


@login_required
def main_report_summary(request):
    try:
        day = request.session.get('day' or None)
        prod_id = request.session.get('production_line' or None)
        production_line = ProductionLine.objects.get(id=prod_id)
        execution_qs = Report.objects.filter_by_line_and_day(
            day, prod_id).aggregate_execution()['execution__sum']
        plan_qs = Report.objects.filter_by_line_and_day(
            day, prod_id).aggregate_plan()['plan__sum']
        problems = ProblemReported.objects.get_problem_by_day_and_line(
            day, production_line)
    except:
        return redirect('reports:select_report')
    context = {
        'execution_qs': execution_qs,
        'plan_qs': plan_qs,
        'day': day,
        'production_line': production_line,
        'problems': problems,
    }

    del request.session['day']
    del request.session['production_line']

    return render(request, 'reports/summary.html', context)


@login_required
def report_view(request, production_line):
    form = ReportForm(request.POST or None, production_line=production_line)
    pform = ProblemReportedForm(request.POST or None)
    queryset = Report.objects.filter(production_line__name=production_line)
    # return the production line or 404 if not created yet
    line = get_object_or_404(ProductionLine, name=production_line)

    if "submitbtn1" in request.POST:
        r_id = request.POST.get("report_id")
        if pform.is_valid():
            report = Report.objects.get(id=r_id)
            new_problem = pform.save(commit=False)
            new_problem.user = request.user
            new_problem.report = report
            new_problem.save()
            # form = ReportForm()
            # pform = ProblemReportedForm()
            return redirect(request.META.get('HTTP_REFERER'))
    elif "submitbtn2" in request.POST:
        if form.is_valid():
            new_report = form.save(commit=False)
            new_report.user = request.user
            new_report.production_line = line
            new_report.save()
            # form = ReportForm()
            # pform = ProblemReportedForm()
            return redirect(request.META.get('HTTP_REFERER'))

    context = {
        'form': form,
        'pform': pform,
        'report_list': queryset,
    }

    return render(request, 'reports/report.html', context)


@login_required
def delete_report(request, *args, **kwargs):
    r_id = kwargs.get('pk')
    report = Report.objects.get(id=r_id)
    report.delete()
    return redirect(request.META.get('HTTP_REFERER'))


class UpdateReportView(LoginRequiredMixin, UpdateView):
    model = Report
    form_class = ReportForm
    template_name = 'reports/update.html'

    def get_success_url(self):
        return self.request.path

src/reports/templates/reports/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Home{% endblock title %}

{% block content %}
    <div class="col-6 mx-auto p-5">
        <div class="text-center text-white h1 mb-5">
            Welcome to Improveo.
        </div>
        {% if request.user.is_authenticated %}
            <form action="" method="post" class="form-group bg-white p-2 rounded">
                <div class="text-muted mb-2 h5">
                    Select a Production Line to begin.
                </div>
                {% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" name="prod_line" id="prod_line">
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        {% else %}
            <div class="text-center text-white h3">
                Login to begin.
            </div>
        {% endif %}
    </div>

    {% block script %}
        <script src="{% static 'scripts.js' %}"></script>
    {% endblock script %}
{% endblock content %}

src/reports/templates/reports/problems.html
<html>
    <head>
        <style type="text/css">
            .tg  {border-collapse:collapse;border-spacing:0;}
            .tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
            overflow:hidden;padding:10px 5px;word-break:normal;}
            .tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
            font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
            .tg .tg-wo29{border-color:#c0c0c0;text-align:left;vertical-align:top}
        </style>
    </head>
    <body>
        {% for p in problems %}
            <h3>Problems</h3>
            <p>{{ p.created }}</p>
            <table class="tg">
                <thead>
                <tr>
                    <th class="tg-wo29">Category</th>
                    <th class="tg-wo29">{{ p.category }}</th>
                </tr>
                <tr>
                    <th class="tg-wo29">Production Line</th>
                    <th class="tg-wo29">{{ p.report.production_line }}</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="tg-wo29">Description</td>
                    <td class="tg-wo29">{{ p.description }}</td>
                </tr>
                <tr>
                    <td class="tg-wo29">ID</td>
                    <td class="tg-wo29">{{ p.problem_id }}</td>
                </tr>
                <tr>
                    <td class="tg-wo29">BreakDown</td>
                    <td class="tg-wo29">{{ p.breakdown }} min{{ p.breakdown|pluralize }}</td>
                </tr>
                </tbody>
            </table>
        {% endfor %}
    </body>
</html>

src/reports/templates/reports/report.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Report{% endblock title %}


{% block content %}
    <!-- Modal for report a problem form -->
    <div class="modal fade" id="problemModal" tabindex="-1" role="dialog" aria-labelledby="problemModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="problemModalLabel">Report A Problem</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="." method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ pform|crispy }}
                        <input type="hidden" name="report_id" id="report_id">
                    
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" name="submitbtn1" class="btn btn-primary">Send</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-white shadow-lg rounded py-2">
        <div class="row">
            <div class="col-2">
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" name="submitbtn2" class="btn btn-primary w-100 shadow-sm mt-3">
                        <i class="far fa-paper-plane pr-3"></i>Send 
                    </button>
                </form>
            </div>

            <div class="col-10">
                <div class="w-100 bg-light rounded border" style="overflow-y:scroll; height:85vh;">
                    <table class="table">
                        <thead class="thead-light">
                            <tr class="text-center">
                                <th scope="col">Day</th>
                                <th scope="col">Start</th>
                                <th scope="col">End</th>
                                <th scope="col">Product</th>
                                <th scope="col">Plan</th>
                                <th scope="col">Execution</th>
                                <th scope="col">Line</th>
                                <th scope="col">Problem</th>
                                <th scope="col">Edit</th>
                                <th scope="col">Delete</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for report in report_list %}
                                <tr class="text-center">
                                    <td>{{ report.get_day }}</td>
                                    <td>{{ report.start_hour }}</td>
                                    <td>{{ report.end_hour }}</td>
                                    <td>{{ report.product }}</td>
                                    <td>{{ report.plan }}</td>
                                    <td>{{ report.execution }}</td>
                                    <td>{{ report.production_line.name }}</td>
                                    <td class="fit">
                                        <button type="submit" class="btn btn-warning open-modals" data-toggle="modal" data-target="#problemModal" data-url="{{ report.id }}">
                                            <i class="fas fa-exclamation-triangle"></i>
                                        </button>
                                    </td>

                                    <td class="fit">
                                        <a href="{{ report.get_absolute_url }}">
                                            <button type="submit" class="btn btn-info">
                                                <i class="far fa-edit"></i>
                                            </button>
                                        </a>
                                    </td>

                                    <td class="fit">
                                        <a href="{% url 'reports:delete_report' pk=report.id %}">
                                            <button type="submit" class="btn btn-danger">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    
    {% block script %}
        <script src="{% static 'scripts.js' %}"></script>
    {% endblock script %}
    
{% endblock content %}

src/reports/templates/reports/select.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Select Report Day{% endblock title %}

{% block content %}
    
    {% block script %}
        <script src="{% static 'scripts.js' %}"></script>
    {% endblock script %}
    


    <div class="col-6 mx-auto p-5">
        <div class="text-center text-white h3 m-5">
            Select a line and a day. 
        </div>
        <form action="" method="post" class="form-group rounded p-3" style="background-color:white;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    
{% endblock content %}

src/reports/templates/reports/summary.html
{% extends 'base.html' %}
{% load status %}
{% load subtract %}
{% block title %}Summary{% endblock title %}

{% block content %}
<div class="container bg-white py-2 rounded">
    <div class="col-12">
        <div class="text-muted h2">
            <i class="fas fa-tachometer-alt mr-3"></i> Results
        </div>
    </div>
    <div class="col">
        Summary Of: <strong>{{ day }} - ( {{ production_line }} )</strong>
    </div>
    <br>
    <table class="table table-sm text-center">
        <thead>
            <tr>
                <th scope="col">Plan</th>
                <th scope="col">Execution</th>
                <th scope="col">Difference</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ plan_qs }}</td>
                <td>{{ execution_qs }}</td>
                <td>{{ execution_qs|subtract:plan_qs }}</td>
                <td>{{ execution_qs|status:plan_qs }}</td>
            </tr>
        </tbody>
    </table>
    <br>
    <h3>Problems</h3>
    <hr>
    {% for problem in problems %}
        <small class="text-muted">{{ problem.problem_id }}</small><br>
        {{ problem.category }}<br>
        {{ problem.description }}<br>
        {{ problem.breakdown }} min{{ problem.breakdown|pluralize }}<br>
        <hr>
    {% endfor %}
</div>
{% endblock content %}

src/reports/templates/reports/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update Report{% endblock title %}

{% block content %}
    <div class="col-9 mx-auto">
        <div class="card p-4">
            <div class="text-muted mb-4 h4">
                Production Line: {{ object.production_line }}
            </div>
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
{% endblock content %}